
words = [
    "inmate", "inquiry", "intrepid", "invincible", "irresponsible", "jellyfish", "jewelry", "jinx", "judicious", "kafkaesque", 
    "kidneys", "kindness", "kingdom", "leadership", "liable", "light-hearted", "liver", "lorry", "loyalty", "luckily", 
    "lungs", "luxurious", "marvellous", "mate", "mattress", "mediocre", "membership", "mend", "mesmerizing", "meticulous", 
    "misbehave", "mischievous", "miserably", "mishap", "Mississippi", "mnemonic", "motorway", "mourn", "murmuring", "naive", 
    "narcissistic", "neighbourhood", "nettle", "nightlife", "occupants", "outdoorsy", "outskirts", "overcome", "overestimate", 
    "pathology", "pedestrianised", "peeled", "penchant", "persevere", "phenomenon", "philosophical", "Phoenix", "pitiful", 
    "pompous", "pond", "pride", "priestess", "profit", "pseudonym", "psychiatrist", "puke", "pursue", "pushchair", 
    "quantum", "raise", "readily", "rear", "recreate", "recruited", "regardless", "rejuvenate", "relationship", "reliability", 
    "reproachful", "reputable", "reservoir", "retrace", "rhinestone", "rhythm", "sarcastic", "satirised", "scissors", 
    "scorching", "scruffy", "selfishness", "sensitivity", "shades", "shifting", "shutters", "silent", "singularly", 
    "skyscraper", "smirk", "soaking", "soulmate", "soundtrack", "spectacle", "spine", "sportswear", "stabilize", "straighten", 
    "strobe", "stubbly", "stuffed", "stunt", "submissively", "subtly", "suggestions", "sulkiness", "suppositions", "surprisingly", 
    "surveillance", "sweeten", "switch", "sympathize", "tare", "tarnished", "tasteless", "technophobe", "thankful", 
    "thorough", "threaten", "thrive", "through", "tight", "tighten", "tolerance", "toss", "triumph", "troubled", 
    "underground", "undermine", "undoubtedly", "unemployment", "unfaithful", "unguarded", "utterly", "vivacious", "weaken", 
    "wealthy", "weight", "whilst", "whispered", "wholesome", "whomever", "wisdom", "wounded", "wretched", "wrinkled", "zealously"
]

definitions = {
    "inmate": "A person living in a prison or institution.",
    "inquiry": "An act of asking for information.",
    "intrepid": "Fearless and adventurous.",
    "invincible": "Too powerful to be defeated.",
    "irresponsible": "Not showing a proper sense of responsibility.",
    "jellyfish": "A sea animal with a soft, transparent body.",
    "jewelry": "Personal ornaments like necklaces and rings.",
    "jinx": "A person or thing that brings bad luck.",
    "judicious": "Having or showing good judgment.",
    "kafkaesque": "Characteristic of the oppressive world in Kafka's works.",
    "kidneys": "Organs that filter blood in the body.",
    "kindness": "The quality of being friendly and considerate.",
    "kingdom": "A country ruled by a king or queen.",
    "leadership": "The action of leading a group or organization.",
    "liable": "Responsible by law.",
    "light-hearted": "Amusing and entertaining.",
    "liver": "A large organ in the body that cleans blood.",
    "lorry": "A large heavy motor vehicle for transporting goods.",
    "loyalty": "A strong feeling of support or allegiance.",
    "luckily": "It is fortunate that.",
    "lungs": "Organs used for breathing.",
    "luxurious": "Extremely comfortable or elegant.",
    "marvellous": "Causing great wonder; extraordinary.",
    "mate": "A friend or companion.",
    "mattress": "The soft part of a bed to sleep on.",
    "mediocre": "Of only average quality.",
    "membership": "The state of belonging to a group.",
    "mend": "To repair something that is broken.",
    "mesmerizing": "Capturing one's complete attention.",
    "meticulous": "Showing great attention to detail.",
    "misbehave": "To behave badly.",
    "mischievous": "Causing trouble in a playful way.",
    "miserably": "In a very unhappy or uncomfortable way.",
    "mishap": "An unlucky accident.",
    "Mississippi": "A major river in the United States.",
    "mnemonic": "A device such as a pattern of letters to assist memory.",
    "motorway": "A broad highway designed for high-speed traffic.",
    "mourn": "To feel deep sorrow for someone who has died.",
    "murmuring": "Speaking in a low, quiet voice.",
    "naive": "Showing a lack of experience or judgment.",
    "narcissistic": "Having an excessive interest in oneself.",
    "neighbourhood": "A district or community within a town.",
    "nettle": "A plant that stings the skin.",
    "nightlife": "Social activities available at night.",
    "occupants": "People who live in or use a place.",
    "outdoorsy": "Fond of spending time outside.",
    "outskirts": "The outer parts of a town or city.",
    "overcome": "To succeed in dealing with a problem.",
    "overestimate": "To think something is better than it is.",
    "pathology": "The study of diseases.",
    "pedestrianised": "Converted into a zone for walkers only.",
    "peeled": "With the skin or outer layer removed.",
    "penchant": "A strong or habitual liking for something.",
    "persevere": "To continue despite difficulty.",
    "phenomenon": "A remarkable person or thing.",
    "philosophical": "Relating to the study of knowledge.",
    "Phoenix": "A mythical bird that rises from ashes.",
    "pitiful": "Deserving of pity or compassion.",
    "pompous": "Affectedly grand or self-important.",
    "pond": "A small body of still water.",
    "pride": "A feeling of deep pleasure from achievements.",
    "priestess": "A female priest.",
    "profit": "Financial gain.",
    "pseudonym": "A fictitious name used by an author.",
    "psychiatrist": "A doctor who treats mental illness.",
    "puke": "To vomit.",
    "pursue": "To follow or chase.",
    "pushchair": "A folding chair on wheels for a baby.",
    "quantum": "A discrete quantity of energy.",
    "raise": "To lift or move to a higher position.",
    "readily": "Without hesitation or difficulty.",
    "rear": "The back part of something.",
    "recreate": "To create again.",
    "recruited": "Enrolled or enlisted.",
    "regardless": "Without paying attention to.",
    "rejuvenate": "To make look or feel younger.",
    "relationship": "The way in which two people are connected.",
    "reliability": "The quality of being trustworthy.",
    "reproachful": "Expressing disapproval or disappointment.",
    "reputable": "Having a good reputation.",
    "reservoir": "A large natural or artificial lake for water.",
    "retrace": "To go back over the same route.",
    "rhinestone": "An imitation diamond used in jewelry.",
    "rhythm": "A strong, regular repeated pattern of sound.",
    "sarcastic": "Using irony to mock or convey contempt.",
    "satirised": "Mocked or criticized using satire.",
    "scissors": "A tool for cutting paper or cloth.",
    "scorching": "Very hot.",
    "scruffy": "Shabby and untidy.",
    "selfishness": "Caring only about oneself.",
    "sensitivity": "The quality of being quick to detect or respond.",
    "shades": "Sunglasses.",
    "shifting": "Changing position or direction.",
    "shutters": "Hinged panels for a window.",
    "silent": "Making no sound.",
    "singularly": "In a remarkable or noticeable way.",
    "skyscraper": "A very tall building.",
    "smirk": "A smug or conceited smile.",
    "soaking": "Extremely wet.",
    "soulmate": "A person ideally suited to another.",
    "soundtrack": "The music of a film or video game.",
    "spectacle": "A visually striking performance.",
    "spine": "The backbone.",
    "sportswear": "Clothes worn for sport.",
    "stabilize": "To make unlikely to give way.",
    "straighten": "To make or become straight.",
    "strobe": "A high-intensity flashing light.",
    "stubbly": "Covered with short, stiff hair.",
    "stuffed": "Filled with something.",
    "stunt": "A daring action.",
    "submissively": "In a way that shows obedience.",
    "subtly": "In a delicate or precise way.",
    "suggestions": "Ideas or plans put forward.",
    "sulkiness": "A mood of gloomy silence.",
    "suppositions": "Uncertain beliefs.",
    "surprisingly": "In a way that causes surprise.",
    "surveillance": "Close observation.",
    "sweeten": "To make sweet.",
    "switch": "To change or exchange.",
    "sympathize": "To agree with a sentiment or opinion.",
    "tare": "The weight of an empty container.",
    "tarnished": "Lost luster or brightness.",
    "tasteless": "Lacking flavor.",
    "technophobe": "A person who fears technology.",
    "thankful": "Pleased and relieved.",
    "thorough": "Complete with regard to every detail.",
    "threaten": "To express an intention to harm.",
    "thrive": "To grow or develop well.",
    "through": "Moving in one side and out the other.",
    "tight": "Fixed or fastened firmly.",
    "tighten": "To make tight.",
    "tolerance": "The ability to accept something.",
    "toss": "To throw lightly.",
    "triumph": "A great victory or achievement.",
    "troubled": "Beset by problems.",
    "underground": "Beneath the surface of the ground.",
    "undermine": "To damage or weaken.",
    "undoubtedly": "Without doubt.",
    "unemployment": "The state of being without a job.",
    "unfaithful": "Not loyal.",
    "unguarded": "Not protected or watched.",
    "utterly": "Completely and absolutely.",
    "vivacious": "Attractively lively and animated.",
    "weaken": "To make or become weak.",
    "wealthy": "Having a lot of money.",
    "weight": "How heavy something is.",
    "whilst": "During the time that.",
    "whispered": "Spoke very softly.",
    "wholesome": "Conducive to good health.",
    "whomever": "Whatever person.",
    "wisdom": "The quality of having experience and knowledge.",
    "wounded": "Injured.",
    "wretched": "In a very unhappy or unfortunate state.",
    "wrinkled": "Having lines or folds.",
    "zealously": "With great energy or enthusiasm."
}

examples = {
    "inmate": "The **inmate** was released after serving his sentence.",
    "inquiry": "The police launched an **inquiry** into the incident.",
    "intrepid": "The **intrepid** explorer climbed the mountain.",
    "invincible": "The team felt **invincible** after winning every game.",
    "irresponsible": "It was **irresponsible** to leave the door unlocked.",
    "jellyfish": "Be careful of the **jellyfish** when swimming.",
    "jewelry": "She keeps her expensive **jewelry** in a safe.",
    "jinx": "He thinks he is a **jinx** because it always rains when he goes out.",
    "judicious": "Her **judicious** saving allowed her to buy a house.",
    "kafkaesque": "The bureaucratic process was positively **kafkaesque**.",
    "kidneys": "Drink water to keep your **kidneys** healthy.",
    "kindness": "Thank you for your **kindness** and support.",
    "kingdom": "The **kingdom** was peaceful for many years.",
    "leadership": "Good **leadership** is essential for a successful company.",
    "liable": "You are **liable** for any damage you cause.",
    "light-hearted": "It was a **light-hearted** movie with no serious themes.",
    "liver": "The **liver** processes toxins in the body.",
    "lorry": "The **lorry** delivered the goods to the warehouse.",
    "loyalty": "The dog showed great **loyalty** to its owner.",
    "luckily": "**Luckily**, I had an umbrella when it started to rain.",
    "lungs": "Smoking can damage your **lungs**.",
    "luxurious": "They stayed in a **luxurious** hotel in Paris.",
    "marvellous": "The view from the top was **marvellous**.",
    "mate": "He's my best **mate** from school.",
    "mattress": "This new **mattress** is very comfortable.",
    "mediocre": "The food was **mediocre**, not great but not terrible.",
    "membership": "Gym **membership** allows you to use all the equipment.",
    "mend": "Can you **mend** the hole in my shirt?",
    "mesmerizing": "The dancer's performance was **mesmerizing**.",
    "meticulous": "He was **meticulous** about keeping his desk tidy.",
    "misbehave": "If you **misbehave**, you won't get any dessert.",
    "mischievous": "The **mischievous** puppy hid my shoe.",
    "miserably": "The team failed **miserably** in the final match.",
    "mishap": "Despite a small **mishap**, the event went well.",
    "Mississippi": "The **Mississippi** River is one of the longest in the world.",
    "mnemonic": "ROYGBIV is a **mnemonic** for the colors of the rainbow.",
    "motorway": "We drove on the **motorway** to get there faster.",
    "mourn": "People gathered to **mourn** the loss of the leader.",
    "murmuring": "I heard someone **murmuring** in the next room.",
    "naive": "It was **naive** to think the job would be easy.",
    "narcissistic": "His **narcissistic** behavior annoyed his colleagues.",
    "neighbourhood": "It's a quiet and friendly **neighbourhood**.",
    "nettle": "Don't touch that **nettle**, it will sting you.",
    "nightlife": "The city is famous for its vibrant **nightlife**.",
    "occupants": "The **occupants** of the car were unhurt.",
    "outdoorsy": "She is very **outdoorsy** and loves hiking.",
    "outskirts": "They live on the **outskirts** of London.",
    "overcome": "He managed to **overcome** his fear of heights.",
    "overestimate": "Don't **overestimate** your ability to finish quickly.",
    "pathology": "The **pathology** report confirmed the diagnosis.",
    "pedestrianised": "The city center has been **pedestrianised**.",
    "peeled": "She **peeled** the apple before eating it.",
    "penchant": "He has a **penchant** for expensive cars.",
    "persevere": "You must **persevere** even when things get tough.",
    "phenomenon": "The northern lights are a natural **phenomenon**.",
    "philosophical": "They had a **philosophical** discussion about life.",
    "Phoenix": "Like a **Phoenix**, the city rose from the ashes.",
    "pitiful": "The stray cat looked **pitiful** in the rain.",
    "pompous": "The politician gave a **pompous** speech.",
    "pond": "Ducks were swimming in the **pond**.",
    "pride": "He took great **pride** in his work.",
    "priestess": "The high **priestess** led the ceremony.",
    "profit": "The company made a huge **profit** this year.",
    "pseudonym": "Mark Twain wrote under a **pseudonym**.",
    "psychiatrist": "She visited a **psychiatrist** for her anxiety.",
    "puke": "The smell made him want to **puke**.",
    "pursue": "He decided to **pursue** a career in medicine.",
    "pushchair": "She put the baby in the **pushchair**.",
    "quantum": "**Quantum** physics explains how atoms work.",
    "raise": "Please **raise** your hand if you have a question.",
    "readily": "He **readily** agreed to help us.",
    "rear": "The garden is at the **rear** of the house.",
    "recreate": "They tried to **recreate** the famous painting.",
    "recruited": "She was **recruited** by a top law firm.",
    "regardless": "I will do it **regardless** of the cost.",
    "rejuvenate": "A spa day will **rejuvenate** you.",
    "relationship": "They have a very strong **relationship**.",
    "reliability": "The car is known for its **reliability**.",
    "reproachful": "She gave him a **reproachful** look.",
    "reputable": "Buy from a **reputable** dealer.",
    "reservoir": "The **reservoir** supplies water to the city.",
    "retrace": "We had to **retrace** our steps to find the keys.",
    "rhinestone": "Her dress was covered in **rhinestones**.",
    "rhythm": "The song has a catchy **rhythm**.",
    "sarcastic": "His **sarcastic** comment made everyone laugh.",
    "satirised": "The play **satirised** political life.",
    "scissors": "Use **scissors** to cut the paper.",
    "scorching": "It was a **scorching** hot day.",
    "scruffy": "He looked **scruffy** in his old clothes.",
    "selfishness": "His **selfishness** caused problems for the team.",
    "sensitivity": "She handled the matter with great **sensitivity**.",
    "shades": "He wore his **shades** to protect his eyes.",
    "shifting": "The wind is **shifting** to the north.",
    "shutters": "Close the **shutters** to keep the sun out.",
    "silent": "The library was completely **silent**.",
    "singularly": "It was a **singularly** beautiful sunset.",
    "skyscraper": "The **skyscraper** dominated the skyline.",
    "smirk": "Wipe that **smirk** off your face.",
    "soaking": "I got **soaking** wet in the rain.",
    "soulmate": "She felt she had met her **soulmate**.",
    "soundtrack": "The movie has an amazing **soundtrack**.",
    "spectacle": "The opening ceremony was a grand **spectacle**.",
    "spine": "The **spine** supports the back.",
    "sportswear": "She was wearing comfortable **sportswear**.",
    "stabilize": "Doctors managed to **stabilize** the patient.",
    "straighten": "Please **straighten** your tie.",
    "strobe": "The **strobe** lights flashed at the disco.",
    "stubbly": "He had a **stubbly** chin after not shaving.",
    "stuffed": "The toy bear was **stuffed** with cotton.",
    "stunt": "The movie featured a dangerous **stunt**.",
    "submissively": "He nodded **submissively** to the boss.",
    "subtly": "The flavor changed **subtly** over time.",
    "suggestions": "I am open to **suggestions**.",
    "sulkiness": "Her **sulkiness** spoiled the party.",
    "suppositions": "His theory was based on **suppositions**.",
    "surprisingly": "The test was **surprisingly** easy.",
    "surveillance": "The bank is under 24-hour **surveillance**.",
    "sweeten": "Add sugar to **sweeten** the tea.",
    "switch": "Please **switch** off the lights.",
    "sympathize": "I **sympathize** with your situation.",
    "tare": "Adjust the scale to account for the **tare** weight.",
    "tarnished": "The silver spoon was **tarnished**.",
    "tasteless": "The soup was bland and **tasteless**.",
    "technophobe": "My grandfather is a bit of a **technophobe**.",
    "thankful": "I am **thankful** for your help.",
    "thorough": "He did a **thorough** search of the room.",
    "threaten": "Don't **threaten** me with violence.",
    "thrive": "Plants **thrive** with sunlight and water.",
    "through": "We walked **through** the forest.",
    "tight": "These shoes are too **tight**.",
    "tighten": "You need to **tighten** the screw.",
    "tolerance": "We must show **tolerance** for other cultures.",
    "toss": "**Toss** the ball to me.",
    "triumph": "The victory was a great **triumph**.",
    "troubled": "He looked **troubled** by the news.",
    "underground": "The train travels **underground**.",
    "undermine": "To damage or weaken.",
    "undoubtedly": "She is **undoubtedly** the best player.",
    "unemployment": "High **unemployment** is a serious issue.",
    "unfaithful": "He was **unfaithful** to his wife.",
    "unguarded": "The gate was left **unguarded**.",
    "utterly": "I was **utterly** exhausted.",
    "vivacious": "She has a **vivacious** personality.",
    "weaken": "The storm began to **weaken**.",
    "wealthy": "A **wealthy** businessman bought the painting.",
    "weight": "The **weight** of the box is 10kg.",
    "whilst": "He read **whilst** waiting for the train.",
    "whispered": "She **whispered** a secret in my ear.",
    "wholesome": "They ate a **wholesome** meal.",
    "whomever": "Give it to **whomever** you like.",
    "wisdom": "Age brings **wisdom**.",
    "wounded": "The **wounded** soldier was carried away.",
    "wretched": "I felt **wretched** after the flu.",
    "wrinkled": "His shirt was **wrinkled**.",
    "zealously": "He **zealously** guarded his privacy."
}

print("Definitions Patch:")
for w in words:
    if w in definitions:
        print(f"            '{w}': '{definitions[w]}',")

print("\nExamples Patch:")
for w in words:
    if w in examples:
        print(f"            '{w}': '{examples[w]}',")
